services:

  postgres:
    image: postgres:16-alpine
    container_name: postgres-db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aansa.123
      POSTGRES_DB: userdb

    ports:
      - "5432:5432"

    volumes:
      - user_postgres_data:/var/lib/postgresql/data
  user-api:
    build: .

    container_name: user-api

    restart: always

    depends_on:
      - postgres

    ports:
      - "3000:3000"

    environment:
      DATABASE_URL: postgresql://postgres:Aansa.123@postgres:5432/userdb?schema=public
      JWT_SECRET: 6CuBxiKHF3rGbnnjg4IXp6yfnHUanHdPRkeiASaEhIS
      JWT_EXPIRES_IN: 7d

volumes:
  user_postgres_data:
    external: true
      