name: User Service CI/CD

permissions:
  contents: write

on:
  push:
    branches:
      - dev
      - staging
      - main

  pull_request:
    branches:
      - dev
      - staging
      - main


jobs:

  # =========================
  # CI
  # =========================
  ci:
    name: Test User Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test


  # =========================
  # Build and Push Docker Image
  # =========================
  docker:
    name: Build and Push Docker Image
    needs: ci

    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.tag.outputs.image_tag }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Image Tag
        id: tag
        run: |
          if [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            TAG="dev-${GITHUB_RUN_NUMBER}"
          elif [[ "${GITHUB_REF_NAME}" == "staging" ]]; then
            TAG="staging-${GITHUB_RUN_NUMBER}"
          elif [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            TAG="main-${GITHUB_RUN_NUMBER}"
          fi

          echo "image_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/user-service:${{ steps.tag.outputs.image_tag }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/user-service:${{ steps.tag.outputs.image_tag }}

  gitops:
    name: Update GitOps Repository

    needs: docker

    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:

      - name: Checkout GitOps Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.GITOPS_REPO }}
          token: ${{ secrets.GITOPS_PAT }}
          ref: ${{ github.ref_name }}

      - name: Update Deployment Image
        run: |
          sed -i "s|image: .*|image: aansa123/user-service:${{ needs.docker.outputs.image_tag }}|" user-api-k8s/deployment.yaml

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          git commit -m "Update User Service image to ${{ needs.docker.outputs.image_tag }}" || echo "No changes"

      - name: Push Changes
        run: |
          git push